[package]
name = "portfolio-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
include_dir = "0.7.4"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = {version = "0.12.9", features = ["json"] }

rocket = "0.5.1"

rocket-include-dir = "1.1.0"
serde_json = "1.0.133"

